class OpenGLEXTConstant {
  int UNPACK_FLIP_Y_WEBGL = 0x9240;
  int UNPACK_PREMULTIPLY_ALPHA_WEBGL = 0x9241;
  int MAX_TEXTURE_MAX_ANISOTROPY_EXT = 0x84FF;

  int TEXTURE_MAX_ANISOTROPY_EXT = 34046;
}
